# Generated by Django 4.1.1 on 2022-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('college_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('hostel', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabDress',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('college_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('hostel', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('taken', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('added_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
