# Generated by Django 4.1.1 on 2022-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labdress',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
